# Generated by Django 2.2.28 on 2023-07-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='viewed_sp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.PositiveIntegerField(default=0, verbose_name='eid')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('type', models.PositiveIntegerField(choices=[(1, '普通属性'), (2, '度量属性(聚合值)')], default=1, verbose_name='type')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='rank')),
                ('state', models.PositiveIntegerField(choices=[(0, '不显示'), (1, '显示')], default=0, verbose_name='state')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='created')),
            ],
        ),
    ]
