# Generated by Django 2.2.28 on 2023-11-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0002_report_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_task',
            name='UpdateTime',
            field=models.DateTimeField(),
        ),
    ]
